kind: ConfigMap
metadata:
  name: {{ include "zeebe-operate.fullname" . }}
apiVersion: v1
data:
  application.yml: |
    # Operate configuration file
    camunda.operate:
      # ELS instance to store Operate data
      elasticsearch:
        # Cluster name
        clusterName: elasticsearch
        # Host
        host: {{ .Values.global.elasticsearch.host }}
        # Transport port
        port: {{ .Values.global.elasticsearch.port }}
      # Zeebe instance
      zeebe:
        # Broker contact point
        brokerContactPoint: {{ tpl .Values.global.zeebe . }}:26500
      # ELS instance to export Zeebe data to
      zeebeElasticsearch:
        # Cluster name
        clusterName: elasticsearch
        # Host
        host: {{ .Values.global.elasticsearch.host }}
        # Transport port
        port: {{ .Values.global.elasticsearch.port }}
        # Index prefix, configured in Zeebe Elasticsearch exporter
        prefix: zeebe-record
    logging:
      level:
        ROOT: INFO
        org.camunda.operate: DEBUG
    #Spring Boot Actuator endpoints to be exposed
    management.endpoints.web.exposure.include: health,info,conditions,configprops,prometheus